---
- name: Ensure apt cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install PostgreSQL packages
  apt:
    name:
      - postgresql
      - postgresql-contrib
    state: present

- name: Ensure PostgreSQL service is running and enabled
  service:
    name: postgresql
    state: started
    enabled: yes
